"""The documentation gate must reject suggestions even when Vale exits zero."""
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]


@unittest.skipUnless(shutil.which('vale'), 'Documentation gate requires Vale')
class DocumentationTests(unittest.TestCase):
    def test_suggestion_fails_gate(self):
        self.assertTrue((ROOT / 'scripts/check_docs.py').exists(), 'Strict documentation gate is required')
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / 'example.md'
            path.write_text('Do not edit this file.\n')
            result = subprocess.run([sys.executable, str(ROOT / 'scripts/check_docs.py'), str(path)], capture_output=True, text=True)
            self.assertEqual(result.returncode, 1, result.stderr + result.stdout)
            self.assertIn('Google.Contractions', result.stdout)

    def test_clean_document_passes_gate(self):
        self.assertTrue((ROOT / 'scripts/check_docs.py').exists(), 'Strict documentation gate is required')
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / 'example.md'
            path.write_text('Use this file for testing.\n')
            result = subprocess.run([sys.executable, str(ROOT / 'scripts/check_docs.py'), str(path)], capture_output=True, text=True)
            self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
