"""The documentation gate must reject suggestions even when Vale exits zero."""
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]


@unittest.skipUnless(shutil.which('vale'), 'Documentation gate requires Vale')
class DocumentationTests(unittest.TestCase):
    def test_suggestion_fails_gate(self):
        self.assertTrue((ROOT / 'scripts/check_docs.py').exists(), 'Strict documentation gate is required')
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / 'example.md'
            path.write_text('Do not edit this file.\n')
            result = subprocess.run([sys.executable, str(ROOT / 'scripts/check_docs.py'), str(path)], capture_output=True, text=True)
            self.assertEqual(result.returncode, 1, result.stderr + result.stdout)
            self.assertIn('Google.Contractions', result.stdout)

    def test_clean_document_passes_gate(self):
        self.assertTrue((ROOT / 'scripts/check_docs.py').exists(), 'Strict documentation gate is required')
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / 'example.md'
            path.write_text('Use this file for testing.\n')
            result = subprocess.run([sys.executable, str(ROOT / 'scripts/check_docs.py'), str(path)], capture_output=True, text=True)
            self.assertEqual(result.returncode, 0, result.stderr + result.stdout)

    def test_default_gate_checks_evaluation_guide(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / 'scripts').mkdir()
            (root / 'evals').mkdir()
            shutil.copy2(ROOT / 'scripts/check_docs.py', root / 'scripts/check_docs.py')
            shutil.copytree(ROOT / 'plugins', root / 'plugins')
            (root / 'README.md').write_text('Use this guide.\n')
            (root / 'evals/README.md').write_text('Do not edit this file.\n')
            result = subprocess.run([sys.executable, str(root / 'scripts/check_docs.py')], capture_output=True, text=True)
            self.assertEqual(result.returncode, 1, result.stderr + result.stdout)
            self.assertIn('evals/README.md', result.stdout)
            self.assertIn('Google.Contractions', result.stdout)
